### ISSUE TITLE
阿里云支持logback为什么还封装一个呢？

### ISSUE THREAD

**Issue by YooLin** [kekingcn/aliyunlog-spring-boot-starter#4]
https://github.com/aliyun/aliyun-log-logback-appender
这样集成不是更简单方便吗？

**Comment by klboke** [comment]
http://kailing.pub/article/index/arcid/264.html 为什么搞这么一个组件。看下我的博客关于原生SDK接入的痛点

**Comment by YooLin** [comment]
谢谢解惑，之前没看到相关文章。
